version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: odc_pass
      MYSQL_DATABASE: estimate
      MYSQL_USER: admin
      MYSQL_PASSWORD: odc_pass
    ports:
      - '3306:3306'
    networks:
      mysql-phpmyadmin:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      mysql-phpmyadmin:

networks:
  mysql-phpmyadmin:

volumes:
  mysql:
